#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 50


#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 743278758
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false
  task:
    execution:
      pool:
        queue-capacity: 128
        core-size: 5
        max-size: 10
        keep-alive: 60000
    
    
#mybatis
mybatis:
  configuration:
  #默认超时时间30s
    default-statement-timeout: 30
    #支持驼峰命名转下划线
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
    
#log
logging:
  level:
    com.cy: DEBUG
